enableGlobalCache: false

nodeLinker: pnpm

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  "langium@*":
    dependencies:
      "vscode-jsonrpc": "8.0.2"
      "vscode-languageserver-protocol": "3.17.2"
      "vscode-languageserver-types": "3.17.2"
      "regexp-to-ast": "^0.5.0"
  "langium-cli@*":
    dependencies:
      "vscode-uri": "3.0.7"
  "@vscode/webview-ui-toolkit@*":
    dependencies:
      "@microsoft/fast-web-utilities": "*"
      "tslib": "^2.5.0"
