enableGlobalCache: false

nmMode: hardlinks-local

nodeLinker: node-modules

npmPublishRegistry: https://registry.npmjs.org

npmScopes:
  "likec4":
    npmRegistryServer: https://registry.npmjs.org
    npmAuthToken: ${NPM_AUTH_TOKEN:-}

packageExtensions:
  "@vscode/webview-ui-toolkit@*":
    dependencies:
      "@microsoft/fast-web-utilities": "*"
      tslib: ^2.5.0
  langium-cli@*:
    dependencies:
      vscode-uri: 3.0.7
  langium@*:
    dependencies:
      regexp-to-ast: ^0.5.0
      vscode-jsonrpc: 8.0.2
      vscode-languageserver-protocol: 3.17.2
      vscode-languageserver-types: 3.17.2

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

preferInteractive: true

supportedArchitectures:
  cpu:
    - x64
    - arm64

yarnPath: .yarn/releases/yarn-3.4.1.cjs
