enableGlobalCache: false
preferInteractive: true
enableTelemetry: false
enableInlineBuilds: true

nmMode: hardlinks-global
nodeLinker: node-modules

npmPublishAccess: public
npmScopes:
  "likec4":
    npmPublishRegistry: https://registry.npmjs.org
    npmAuthToken: ${NPM_AUTH_TOKEN:-}

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

supportedArchitectures:
  os:
    - current
  cpu:
    - current

yarnPath: .yarn/releases/yarn-3.4.1.cjs

changesetIgnorePatterns:
  - "**/__tests__/**"
  - "**/__mock__/**"
  - "**/*.spec.{ts,tsx}"
