version: '3'

tasks:
  release:
    dotenv: ['.env']
    cmds:
      # - yarn workspaces foreach --topological-dev version minor
      - yarn version check --interactive
      - yarn compile && yarn clean && yarn build:release
      - yarn version apply --all
      - yarn workspaces foreach --topological-dev --no-private --exclude=likec4-vscode npm publish
      - yarn clean:after:publish
