name: main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  actions: write
  checks: write
  contents: read
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-main:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: ./.github/actions/bootstrap

      - name: turborepo-cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build packages
        run: yarn build

      - name: Compile
        run: yarn compile:all

      - name: Test
        run: yarn test

  release:
    uses: ./.github/workflows/release.yaml
    if: "contains(github.event.head_commit.message, 'chore: release')"
    needs: build-main
    permissions:
      actions: write
      checks: write
      contents: write
      statuses: write
    secrets: inherit

  publish-docs:
    uses: ./.github/workflows/docs.yaml
    needs: build-main
    permissions:
      actions: write
      contents: read
    secrets: inherit
