name: main

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'develop'

permissions:
  actions: write
  checks: write
  contents: read
  statuses: write

env:
  TURBO_API: 'http://127.0.0.1:9080'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: 'likec4'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          turborepo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build packages
        run: yarn build

  compile:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          turborepo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile all sources
        run: yarn compile:all

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          turborepo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        run: yarn test

  build-docs:
    name: build docs
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          turborepo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: NextJS cache
        if: github.ref == 'refs/heads/main'
        uses: actions/cache@v3
        with:
          path: docs/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('docs/**/*.tsx?', 'docs/**/*.mdx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

      - name: Build NextJS
        working-directory: docs
        run: yarn turbo-build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: likec4-docs
          workingDirectory: docs
          directory: out
