name: main

on:
  push:
    branches:
      - 'main'
    tags-ignore:
      - '**'

permissions:
  actions: write
  checks: write
  contents: write
  statuses: write
  deployments: write

env:
  NODE_ENV: production
  TURBO_CACHE_DIR: ${{ github.workspace }}/.turbo

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    concurrency:
      group: ${{ github.workflow }}-update-cache
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: bootstrap
        uses: ./.github/actions/bootstrap

      - name: typecheck
        run: yarn typecheck:all

      - name: test
        env:
          NODE_ENV: test
        run: yarn ci:test

      - name: build
        run: yarn build:all

  release:
    uses: ./.github/workflows/release.yaml
    if: "contains(github.event.head_commit.message, 'chore: release')"
    needs: build
    concurrency:
      group: ${{ github.workflow }}-release
    secrets: inherit

  vscode:
    uses: ./.github/workflows/vscode.yaml
    if: "contains(github.event.head_commit.message, 'chore: release')"
    needs: build
    concurrency:
      group: ${{ github.workflow }}-vscode
    secrets: inherit

  playground:
    needs: build
    name: playground.likec4.dev
    uses: ./.github/workflows/playground.yaml
    secrets: inherit

  docs:
    needs: build
    name: docs.likec4.dev
    uses: ./.github/workflows/docs.yaml
    secrets: inherit
