name: pull-request

on:
  workflow_dispatch:
  push:
    branches:
      - 'renovate/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - '**/*'

env:
  TURBO_API: 'http://127.0.0.1:9080'
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: 'likec4'
  NODE_ENV: 'production'

permissions:
  actions: read
  checks: write
  contents: read
  statuses: write
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          turborepo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build packages
        run: yarn build

      - name: Test
        run: yarn test

      - name: Compile
        run: yarn compile:all
