name: push

on:
  pull_request:
  push:
    tags-ignore:
      - "**"
    branches-ignore:
      - "main"
      - "releases/*"

concurrency:
  group:  ${{ github.workflow }}-${{github.event_name}}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: production

jobs:
  build:
    # If on pull request, run only if coming from forked repos
    if: |
      !contains(github.event.head_commit.message, 'ci skip') && (
        github.event_name == 'push' || github.event.pull_request.head.repo.fork
      )
    timeout-minutes: 10
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        node-version: ['18', '20']
        include:

          # Build on Windows only with Node 20
          - os: windows-latest
            node-version: '20'

          - os: ubuntu-latest
            node-version: '20'
            build-docs: true

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Bootstrap
        uses: ./.github/actions/bootstrap
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: yarn ci:build

      - name: TypeCheck
        run: yarn typecheck

      - name: Test
        env:
          NODE_ENV: test
        run: yarn ci:test

      - if: ${{ matrix.build-docs }}
        name: Build Docs
        working-directory: docs
        run: yarn build:turbo
