name: push

on:
  pull_request:
  push:
    tags-ignore:
      - "**"
    branches-ignore:
      - "main"
      - "releases/*"

concurrency:
  group:  ${{ github.workflow }}-${{github.event_name}}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

env:
  NODE_ENV: production
  TURBO_CACHE_DIR: ${{ github.workspace }}/.turbo

jobs:
  check-packages:
    # If on pull request, run only if coming from forked repos
    if: |
      !contains(github.event.head_commit.message, 'ci skip') && (
        github.event_name == 'push' || github.event.pull_request.head.repo.fork
      )
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ github.ref }}

      - name: bootstrap
        uses: ./.github/actions/bootstrap
        # with:
        #   node-version: ${{ matrix.node-version }}

      - name: generate
        run: yarn ci:generate

      - name: typecheck
        run: yarn ci:typecheck

      - name: build
        run: yarn ci:build

      - name: test
        run: yarn ci:test

      - name: pack
        working-directory: packages/likec4
        run: yarn pack

      - name: upload artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4
        with:
          name: likec4-package
          if-no-files-found: error
          path: packages/likec4/package.tgz
          retention-days: 5
          compression-level: 0

  check-playground:
    # If on pull request, run only if coming from forked repos
    if: |
      !contains(github.event.head_commit.message, 'ci skip') && (
        github.event_name == 'push' || github.event.pull_request.head.repo.fork
      )
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ github.ref }}

      - name: bootstrap
        uses: ./.github/actions/bootstrap

      - name: typecheck
        run: |
          yarn turbo run typecheck --filter='@likec4/playground'

      - name: build
        run: |
          yarn turbo run build --filter='@likec4/playground'

  check-docs-astro:
    # If on pull request, run only if coming from forked repos
    if: |
      !contains(github.event.head_commit.message, 'ci skip') && (
        github.event_name == 'push' || github.event.pull_request.head.repo.fork
      )
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: bootstrap
        uses: ./.github/actions/bootstrap

      - name: typecheck
        run: |
          yarn turbo run typecheck --filter='@likec4/docs-astro'

      - name: build
        run: |
          yarn turbo run build --filter='@likec4/docs-astro'
