name: release

on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  statuses: write

jobs:
  ship:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: ./.github/actions/bootstrap

      - name: turborepo-cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Build
        run: yarn build

      - name: Release
        run: yarn shipjs trigger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  vscode:
    uses: ./.github/workflows/vscode.yaml
    needs: ship
    permissions:
      actions: write
      contents: read
    secrets: inherit
