name: release

on:
  workflow_call:
  # workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  statuses: write

env:
  NODE_ENV: production

jobs:
  publish-release:
    name: publish
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: "github.ref == 'refs/heads/main'"
    steps:
      - uses: wow-actions/use-app-token@v2
        with:
          fallback: ${{ secrets.GITHUB_TOKEN }}
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ env.BOT_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: turborepo-cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Configure git user
        run: |
          git config user.name "${{ env.BOT_NAME }}[bot]"
          git config user.email "${{ env.BOT_NAME }}[bot]@users.noreply.github.com"

      - name: Release
        run: yarn shipjs trigger
        env:
          GITHUB_TOKEN: ${{ env.BOT_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
