name: vscode

on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

env:
  NODE_ENV: production

jobs:
  publish:
    name: Publish Extension
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # if triggered by workflow_dispatch or
    # by workflow_call on main with a commit message containing "chore: release"
    if: |
      github.event_name == 'workflow_dispatch' || (
        contains(github.event.head_commit.message, 'chore: release')
      )
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Bootstrap
        uses: ./.github/actions/bootstrap

      - name: turborepo-cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: vsce publish
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo " version: $VERSION"
          yarn vsce publish $VERSION
        working-directory: packages/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
