name: vscode

on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  vsce-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: setup
        uses: ./.github/actions/bootstrap

      - name: turborepo-cache
        uses: dtinth/setup-github-actions-caching-for-turbo@v1

      - name: Publish VSCode extension
        run: |
          VERSION=$(node -e "console.log(require('./package.json').version)")
          echo " version: $VERSION"
          yarn vsce publish $VERSION
        working-directory: packages/vscode
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
